[package]
name = "rust-ipld-hamt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fvm_ipld_hamt = "*"
forest_db = "*"
parking_lot = "*"
fvm_ipld_blockstore = "*"
anyhow = "*"
cid = "=0.8.5"
